// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trader.Backend.Api.AppContext;

#nullable disable

namespace Trader.Backend.Api.Migrations
{
    [DbContext(typeof(TraderAppContext))]
    partial class TraderAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("traderapi")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tracker.Backend.Domain.Models.TradeAccount", b =>
                {
                    b.Property<int>("TradeAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TradeAccountId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TradeAccountId");

                    b.ToTable("TradeAccounts", "traderapi");

                    b.HasData(
                        new
                        {
                            TradeAccountId = 1,
                            Name = "T-001"
                        });
                });

            modelBuilder.Entity("Tracker.Backend.Domain.Models.TradeRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AsOfDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FromCurrency")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<decimal>("RateAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ToCurrency")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.HasKey("Id");

                    b.ToTable("TradeRates", "traderapi");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AsOfDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FromCurrency = "EUR",
                            RateAmount = 1.09m,
                            ToCurrency = "USD"
                        });
                });

            modelBuilder.Entity("Tracker.Backend.Domain.Models.TradeTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("TradeAccountId")
                        .HasColumnType("int");

                    b.Property<int>("TradeRateId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TradeTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TradeAccountId");

                    b.ToTable("TradeTransactions", "traderapi");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Currency = "USD",
                            Price = 100m,
                            Quantity = 100,
                            Side = "Side1",
                            Symbol = "Symbol1",
                            TradeAccountId = 1,
                            TradeRateId = 1,
                            TradeTime = new DateTime(2026, 3, 14, 17, 39, 59, 720, DateTimeKind.Local).AddTicks(5189)
                        },
                        new
                        {
                            Id = 2,
                            Currency = "USD",
                            Price = 250m,
                            Quantity = 50,
                            Side = "Side2",
                            Symbol = "Symbol2",
                            TradeAccountId = 1,
                            TradeRateId = 1,
                            TradeTime = new DateTime(2026, 3, 14, 17, 39, 59, 720, DateTimeKind.Local).AddTicks(5211)
                        });
                });

            modelBuilder.Entity("Tracker.Backend.Domain.Models.TradeTransaction", b =>
                {
                    b.HasOne("Tracker.Backend.Domain.Models.TradeAccount", "TradeAccount")
                        .WithMany("TradeTransactions")
                        .HasForeignKey("TradeAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TradeAccount");
                });

            modelBuilder.Entity("Tracker.Backend.Domain.Models.TradeAccount", b =>
                {
                    b.Navigation("TradeTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
