//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TradeRate", Namespace="http://schemas.datacontract.org/2004/07/Tracker.Backend.LegacyService.Data")]
    public partial class TradeRate : object
    {
        
        private System.DateTime AsOfDateField;
        
        private string FromCurrencyField;
        
        private int IdField;
        
        private decimal RateAmountField;
        
        private string ToCurrencyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime AsOfDate
        {
            get
            {
                return this.AsOfDateField;
            }
            set
            {
                this.AsOfDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromCurrency
        {
            get
            {
                return this.FromCurrencyField;
            }
            set
            {
                this.FromCurrencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal RateAmount
        {
            get
            {
                return this.RateAmountField;
            }
            set
            {
                this.RateAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToCurrency
        {
            get
            {
                return this.ToCurrencyField;
            }
            set
            {
                this.ToCurrencyField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfServiceReference.ITraderService")]
    public interface ITraderService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITraderService/GetCurrentRateByCurrency", ReplyAction="http://tempuri.org/ITraderService/GetCurrentRateByCurrencyResponse")]
        System.Threading.Tasks.Task<WcfServiceReference.TradeRate> GetCurrentRateByCurrencyAsync(string selectedCurrency);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface ITraderServiceChannel : WcfServiceReference.ITraderService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class TraderServiceClient : System.ServiceModel.ClientBase<WcfServiceReference.ITraderService>, WcfServiceReference.ITraderService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TraderServiceClient() : 
                base(TraderServiceClient.GetDefaultBinding(), TraderServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ITraderService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TraderServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(TraderServiceClient.GetBindingForEndpoint(endpointConfiguration), TraderServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TraderServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TraderServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TraderServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TraderServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TraderServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<WcfServiceReference.TradeRate> GetCurrentRateByCurrencyAsync(string selectedCurrency)
        {
            return base.Channel.GetCurrentRateByCurrencyAsync(selectedCurrency);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ITraderService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ITraderService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:54528/TraderService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return TraderServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ITraderService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return TraderServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ITraderService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ITraderService,
        }
    }
}
